# Form implementation generated from reading ui file 'D:\UEL\VI Semester\Final_Project\Login.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(302, 447)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 281, 411))
        self.stackedWidget.setStyleSheet("QStackedWidget {\n"
"background-color: rgb(215, 229, 255)\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Welcome = QtWidgets.QWidget()
        self.Welcome.setObjectName("Welcome")
        self.image1 = QtWidgets.QLabel(parent=self.Welcome)
        self.image1.setGeometry(QtCore.QRect(80, 10, 121, 111))
        self.image1.setText("")
        self.image1.setPixmap(QtGui.QPixmap("C:/Users/ADMIN/Pictures/Final_project/tải xuống.png"))
        self.image1.setScaledContents(True)
        self.image1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.image1.setObjectName("image1")
        self.btn_Login = QtWidgets.QPushButton(parent=self.Welcome)
        self.btn_Login.setGeometry(QtCore.QRect(10, 180, 111, 31))
        self.btn_Login.setStyleSheet("QPushButton {\n"
"font-size: 14px\n"
"}")
        self.btn_Login.setObjectName("btn_Login")
        self.btn_Register = QtWidgets.QPushButton(parent=self.Welcome)
        self.btn_Register.setGeometry(QtCore.QRect(160, 180, 111, 31))
        self.btn_Register.setStyleSheet("QPushButton {\n"
"font-size: 14px\n"
"}")
        self.btn_Register.setObjectName("btn_Register")
        self.stackedWidget.addWidget(self.Welcome)
        self.Login = QtWidgets.QWidget()
        self.Login.setObjectName("Login")
        self.image2 = QtWidgets.QLabel(parent=self.Login)
        self.image2.setGeometry(QtCore.QRect(80, 10, 121, 111))
        self.image2.setText("")
        self.image2.setPixmap(QtGui.QPixmap("C:/Users/ADMIN/Pictures/Final_project/tải xuống.png"))
        self.image2.setScaledContents(True)
        self.image2.setObjectName("image2")
        self.label_1 = QtWidgets.QLabel(parent=self.Login)
        self.label_1.setGeometry(QtCore.QRect(90, 130, 101, 41))
        self.label_1.setStyleSheet("QLabel {\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.label_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(parent=self.Login)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 221, 31))
        self.label_2.setStyleSheet("QLabel {\n"
"font-size: 14px;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Email_Label = QtWidgets.QLabel(parent=self.Login)
        self.Email_Label.setGeometry(QtCore.QRect(10, 190, 101, 21))
        self.Email_Label.setStyleSheet("QLabel {\n"
"font-size: 12px;\n"
"}")
        self.Email_Label.setObjectName("Email_Label")
        self.Password_Label = QtWidgets.QLabel(parent=self.Login)
        self.Password_Label.setGeometry(QtCore.QRect(10, 240, 101, 21))
        self.Password_Label.setStyleSheet("QLabel {\n"
"font-size: 12px;\n"
"}")
        self.Password_Label.setObjectName("Password_Label")
        self.Email_LineEdit = QtWidgets.QLineEdit(parent=self.Login)
        self.Email_LineEdit.setGeometry(QtCore.QRect(10, 210, 261, 21))
        self.Email_LineEdit.setStyleSheet("QLineEdit {\n"
"font-size: 12px\n"
"}")
        self.Email_LineEdit.setObjectName("Email_LineEdit")
        self.Password_LineEdit = QtWidgets.QLineEdit(parent=self.Login)
        self.Password_LineEdit.setGeometry(QtCore.QRect(10, 260, 261, 21))
        self.Password_LineEdit.setStyleSheet("QLineEdit {\n"
"font-size: 12px\n"
"}")
        self.Password_LineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Password_LineEdit.setObjectName("Password_LineEdit")
        self.btn_Login_2 = QtWidgets.QPushButton(parent=self.Login)
        self.btn_Login_2.setGeometry(QtCore.QRect(100, 320, 81, 31))
        self.btn_Login_2.setStyleSheet("QPushButton {\n"
"font-size: 14px;\n"
"}")
        self.btn_Login_2.setObjectName("btn_Login_2")
        self.btn_ForgotPass = QtWidgets.QPushButton(parent=self.Login)
        self.btn_ForgotPass.setGeometry(QtCore.QRect(120, 290, 151, 21))
        self.btn_ForgotPass.setStyleSheet("QPushButton {\n"
"background: transparent;\n"
"border: none;\n"
"color: #rgb(123, 123, 123);\n"
"font-size: 12px;\n"
"text-align: right;\n"
"}\n"
"\n"
"")
        self.btn_ForgotPass.setObjectName("btn_ForgotPass")
        self.btn_Back = QtWidgets.QPushButton(parent=self.Login)
        self.btn_Back.setGeometry(QtCore.QRect(10, 10, 56, 17))
        self.btn_Back.setStyleSheet("QPushButton {\n"
"background: transparent;\n"
"border: none;\n"
"color: #rgb(123, 123, 123);\n"
"font-size: 12px;\n"
"text-align: left;\n"
"}\n"
"\n"
"")
        self.btn_Back.setObjectName("btn_Back")
        self.label_3 = QtWidgets.QLabel(parent=self.Login)
        self.label_3.setGeometry(QtCore.QRect(30, 370, 161, 21))
        self.label_3.setStyleSheet("QLabel {\n"
"font-size: 12px;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.btn_Register_2 = QtWidgets.QPushButton(parent=self.Login)
        self.btn_Register_2.setGeometry(QtCore.QRect(170, 370, 71, 21))
        self.btn_Register_2.setStyleSheet("QPushButton {\n"
"    text-decoration: underline;\n"
"    font: 8pt \"MS Shell Dlg 2\";\n"
"background: transparent;\n"
"border: none;\n"
"color: #rgb(123, 123, 123);\n"
"font-size: 12px;\n"
"}\n"
"\n"
"")
        self.btn_Register_2.setObjectName("btn_Register_2")
        self.stackedWidget.addWidget(self.Login)
        self.Register = QtWidgets.QWidget()
        self.Register.setObjectName("Register")
        self.image3 = QtWidgets.QLabel(parent=self.Register)
        self.image3.setGeometry(QtCore.QRect(80, 10, 121, 111))
        self.image3.setText("")
        self.image3.setPixmap(QtGui.QPixmap("C:/Users/ADMIN/Pictures/Final_project/tải xuống.png"))
        self.image3.setScaledContents(True)
        self.image3.setObjectName("image3")
        self.btn_Back_2 = QtWidgets.QPushButton(parent=self.Register)
        self.btn_Back_2.setGeometry(QtCore.QRect(10, 10, 56, 17))
        self.btn_Back_2.setStyleSheet("QPushButton {\n"
"background: transparent;\n"
"border: none;\n"
"color: #rgb(123, 123, 123);\n"
"font-size: 12px;\n"
"text-align: left;\n"
"}\n"
"\n"
"")
        self.btn_Back_2.setObjectName("btn_Back_2")
        self.Password_LineEdit_2 = QtWidgets.QLineEdit(parent=self.Register)
        self.Password_LineEdit_2.setGeometry(QtCore.QRect(10, 300, 261, 21))
        self.Password_LineEdit_2.setStyleSheet("QLineEdit {\n"
"font-size: 12px\n"
"}")
        self.Password_LineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Password_LineEdit_2.setObjectName("Password_LineEdit_2")
        self.UserName_LineEdit = QtWidgets.QLineEdit(parent=self.Register)
        self.UserName_LineEdit.setGeometry(QtCore.QRect(10, 200, 261, 21))
        self.UserName_LineEdit.setStyleSheet("QLineEdit {\n"
"font-size: 12px\n"
"}")
        self.UserName_LineEdit.setObjectName("UserName_LineEdit")
        self.Email_Label_2 = QtWidgets.QLabel(parent=self.Register)
        self.Email_Label_2.setGeometry(QtCore.QRect(10, 230, 101, 21))
        self.Email_Label_2.setStyleSheet("QLabel {\n"
"font-size: 12px;\n"
"}")
        self.Email_Label_2.setObjectName("Email_Label_2")
        self.UserName_Label = QtWidgets.QLabel(parent=self.Register)
        self.UserName_Label.setGeometry(QtCore.QRect(10, 180, 101, 21))
        self.UserName_Label.setStyleSheet("QLabel {\n"
"font-size: 12px;\n"
"}")
        self.UserName_Label.setObjectName("UserName_Label")
        self.Password_Label_2 = QtWidgets.QLabel(parent=self.Register)
        self.Password_Label_2.setGeometry(QtCore.QRect(10, 280, 101, 21))
        self.Password_Label_2.setStyleSheet("QLabel {\n"
"font-size: 12px;\n"
"}")
        self.Password_Label_2.setObjectName("Password_Label_2")
        self.Email_LineEdit_2 = QtWidgets.QLineEdit(parent=self.Register)
        self.Email_LineEdit_2.setGeometry(QtCore.QRect(10, 250, 261, 21))
        self.Email_LineEdit_2.setStyleSheet("QLineEdit {\n"
"font-size: 12px\n"
"}")
        self.Email_LineEdit_2.setObjectName("Email_LineEdit_2")
        self.label_4 = QtWidgets.QLabel(parent=self.Register)
        self.label_4.setGeometry(QtCore.QRect(0, 150, 281, 31))
        self.label_4.setStyleSheet("QLabel {\n"
"font-size: 14px;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.btn_Register_4 = QtWidgets.QPushButton(parent=self.Register)
        self.btn_Register_4.setGeometry(QtCore.QRect(100, 340, 81, 31))
        self.btn_Register_4.setStyleSheet("QPushButton {\n"
"font-size: 14px;\n"
"}")
        self.btn_Register_4.setObjectName("btn_Register_4")
        self.label_5 = QtWidgets.QLabel(parent=self.Register)
        self.label_5.setGeometry(QtCore.QRect(40, 380, 161, 21))
        self.label_5.setStyleSheet("QLabel {\n"
"font-size: 12px;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.btn_Login_3 = QtWidgets.QPushButton(parent=self.Register)
        self.btn_Login_3.setGeometry(QtCore.QRect(170, 380, 71, 21))
        self.btn_Login_3.setStyleSheet("QPushButton {\n"
"    text-decoration: underline;\n"
"    font: 8pt \"MS Shell Dlg 2\";\n"
"background: transparent;\n"
"border: none;\n"
"color: #rgb(123, 123, 123);\n"
"font-size: 12px;\n"
"}\n"
"\n"
"")
        self.btn_Login_3.setObjectName("btn_Login_3")
        self.label_7 = QtWidgets.QLabel(parent=self.Register)
        self.label_7.setGeometry(QtCore.QRect(90, 120, 101, 41))
        self.label_7.setStyleSheet("QLabel {\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.Register)
        self.Reset_Password = QtWidgets.QWidget()
        self.Reset_Password.setObjectName("Reset_Password")
        self.NewPassword_Label = QtWidgets.QLabel(parent=self.Reset_Password)
        self.NewPassword_Label.setGeometry(QtCore.QRect(10, 190, 101, 21))
        self.NewPassword_Label.setStyleSheet("QLabel {\n"
"font-size: 12px;\n"
"}")
        self.NewPassword_Label.setObjectName("NewPassword_Label")
        self.NewPassword_LineEdit = QtWidgets.QLineEdit(parent=self.Reset_Password)
        self.NewPassword_LineEdit.setGeometry(QtCore.QRect(10, 210, 261, 21))
        self.NewPassword_LineEdit.setStyleSheet("QLineEdit {\n"
"font-size: 12px\n"
"}")
        self.NewPassword_LineEdit.setObjectName("NewPassword_LineEdit")
        self.RePassword_Label = QtWidgets.QLabel(parent=self.Reset_Password)
        self.RePassword_Label.setGeometry(QtCore.QRect(10, 260, 231, 21))
        self.RePassword_Label.setStyleSheet("QLabel {\n"
"font-size: 12px;\n"
"}")
        self.RePassword_Label.setObjectName("RePassword_Label")
        self.RePassword_LineEdit = QtWidgets.QLineEdit(parent=self.Reset_Password)
        self.RePassword_LineEdit.setGeometry(QtCore.QRect(10, 280, 261, 21))
        self.RePassword_LineEdit.setStyleSheet("QLineEdit {\n"
"font-size: 12px\n"
"}")
        self.RePassword_LineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.RePassword_LineEdit.setObjectName("RePassword_LineEdit")
        self.image4 = QtWidgets.QLabel(parent=self.Reset_Password)
        self.image4.setGeometry(QtCore.QRect(80, 10, 121, 111))
        self.image4.setText("")
        self.image4.setPixmap(QtGui.QPixmap("C:/Users/ADMIN/Pictures/Final_project/tải xuống.png"))
        self.image4.setScaledContents(True)
        self.image4.setObjectName("image4")
        self.btn_Back_3 = QtWidgets.QPushButton(parent=self.Reset_Password)
        self.btn_Back_3.setGeometry(QtCore.QRect(10, 10, 56, 17))
        self.btn_Back_3.setStyleSheet("QPushButton {\n"
"background: transparent;\n"
"border: none;\n"
"color: #rgb(123, 123, 123);\n"
"font-size: 12px;\n"
"text-align: left;\n"
"}\n"
"\n"
"")
        self.btn_Back_3.setObjectName("btn_Back_3")
        self.label_6 = QtWidgets.QLabel(parent=self.Reset_Password)
        self.label_6.setGeometry(QtCore.QRect(0, 130, 281, 31))
        self.label_6.setStyleSheet("QLabel {\n"
"font-size: 14px;\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.Finish_btn = QtWidgets.QPushButton(parent=self.Reset_Password)
        self.Finish_btn.setGeometry(QtCore.QRect(100, 340, 81, 31))
        self.Finish_btn.setStyleSheet("QPushButton {\n"
"font-size: 14px;\n"
"}")
        self.Finish_btn.setObjectName("Finish_btn")
        self.stackedWidget.addWidget(self.Reset_Password)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 302, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_Login.setText(_translate("MainWindow", "Login"))
        self.btn_Register.setText(_translate("MainWindow", "Register"))
        self.label_1.setText(_translate("MainWindow", "Hello"))
        self.label_2.setText(_translate("MainWindow", "Sign into your Account"))
        self.Email_Label.setText(_translate("MainWindow", "Email:"))
        self.Password_Label.setText(_translate("MainWindow", "Password:"))
        self.btn_Login_2.setText(_translate("MainWindow", "Login"))
        self.btn_ForgotPass.setText(_translate("MainWindow", "Forgot your password?"))
        self.btn_Back.setText(_translate("MainWindow", "< Back"))
        self.label_3.setText(_translate("MainWindow", "Don\'t have an account ?"))
        self.btn_Register_2.setText(_translate("MainWindow", "Register now"))
        self.btn_Back_2.setText(_translate("MainWindow", "< Back"))
        self.Email_Label_2.setText(_translate("MainWindow", "Email:"))
        self.UserName_Label.setText(_translate("MainWindow", "User Name:"))
        self.Password_Label_2.setText(_translate("MainWindow", "Password:"))
        self.label_4.setText(_translate("MainWindow", "Create New Account"))
        self.btn_Register_4.setText(_translate("MainWindow", "Register"))
        self.label_5.setText(_translate("MainWindow", "Already have an account ?"))
        self.btn_Login_3.setText(_translate("MainWindow", "Login"))
        self.label_7.setText(_translate("MainWindow", "Hello"))
        self.NewPassword_Label.setText(_translate("MainWindow", "New Password:"))
        self.RePassword_Label.setText(_translate("MainWindow", "Re - enter New Password:"))
        self.btn_Back_3.setText(_translate("MainWindow", "< Back"))
        self.label_6.setText(_translate("MainWindow", "Reset Password"))
        self.Finish_btn.setText(_translate("MainWindow", "Finish"))
